// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: checkin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CheckinServiceClient is the client API for CheckinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckinServiceClient interface {
	Checkin(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckinResponse, error)
}

type checkinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckinServiceClient(cc grpc.ClientConnInterface) CheckinServiceClient {
	return &checkinServiceClient{cc}
}

func (c *checkinServiceClient) Checkin(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckinResponse, error) {
	out := new(CheckinResponse)
	err := c.cc.Invoke(ctx, "/user.CheckinService/Checkin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckinServiceServer is the server API for CheckinService service.
// All implementations should embed UnimplementedCheckinServiceServer
// for forward compatibility
type CheckinServiceServer interface {
	Checkin(context.Context, *CheckInRequest) (*CheckinResponse, error)
}

// UnimplementedCheckinServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCheckinServiceServer struct {
}

func (UnimplementedCheckinServiceServer) Checkin(context.Context, *CheckInRequest) (*CheckinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkin not implemented")
}

// UnsafeCheckinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckinServiceServer will
// result in compilation errors.
type UnsafeCheckinServiceServer interface {
	mustEmbedUnimplementedCheckinServiceServer()
}

func RegisterCheckinServiceServer(s grpc.ServiceRegistrar, srv CheckinServiceServer) {
	s.RegisterService(&CheckinService_ServiceDesc, srv)
}

func _CheckinService_Checkin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).Checkin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.CheckinService/Checkin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).Checkin(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckinService_ServiceDesc is the grpc.ServiceDesc for CheckinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.CheckinService",
	HandlerType: (*CheckinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Checkin",
			Handler:    _CheckinService_Checkin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkin.proto",
}
