database:
  host: localhost
  port: 3306
  name: rnkm-db
  username: root
  password: root

redis:
  host: localhost
  port: 6379
  password: ""

app:
  port: 3001
  debug: true

service:
  file: localhost:3003
